# Generated by Django 2.2.7 on 2020-03-08 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=6, verbose_name='Horário')),
                ('data_agendamento', models.DateTimeField(auto_now=True, verbose_name='Data do Agendamento')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipe.Agenda', verbose_name='dia')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
        ),
    ]
