# Generated by Django 2.2.7 on 2020-02-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas',
            name='data_agendamento',
            field=models.DateTimeField(auto_now=True, verbose_name='Data do Agendamento'),
        ),
    ]
