# Generated by Django 2.2.7 on 2020-02-28 20:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_consultas_data_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas',
            name='horario',
            field=models.CharField(default=datetime.datetime(2020, 2, 28, 20, 47, 38, 681589, tzinfo=utc), max_length=6, verbose_name='Horário'),
            preserve_default=False,
        ),
    ]
